apiVersion: v1
kind: Service
metadata:
  name: fake-blog-app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tryedition.com
spec:
  selector:
    app: fake-blog-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
