apiVersion: v1
kind: Service
metadata:
  name: fake-blog-app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: tryedition.com
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:651514779373:certificate/c3a16b65-840a-4444-acc0-3c504aa61e51
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    app: fake-blog-app
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      name: http
      targetPort: 3000
   -  protocol: TCP
      port: 443
      name: https
      targetPort: 3000
