apiVersion: v1
kind: Service
metadata:
  name: fake-blog-app
spec:
  selector:
    app: fake-blog-app
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000
